<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"              content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description"           content="Weather App">
    <meta name="keywords"              content="Weather App">

    <title>Weather App</title>    
    
    <link rel="canonical" href="{{ domain|default('') }}" />
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico"> 
    <link href="/vendor/magnific-popup/magnific-popup.css"            rel="stylesheet">
    <link href="/vendor/select2/css/select2.min.css"                  rel="stylesheet">
    <link href="/vendor/slick/slick.css"                              rel="stylesheet">
    <link href="/vendor/font-awesome/css/font-awesome.min.css"        rel="stylesheet">
    <link href="/css/main.css?ver=01"                                 rel="stylesheet">
    <link href="/css/custom.css?ver=01"                               rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700&amp;subset=latin-ext" rel="stylesheet">
    <link href="/font/icons/style.css"                                rel="stylesheet">
    <script src="/vendor/snap.svg-min.js"></script>
    <script src="/vendor/modernizr.min.js"></script>
</head>

<body>
    <div class="c-site-wrapper" id="app">        
        <div class="c-off-canvas">
            <div class="c-off-canvas__inner">
                <nav class="c-off-canvas__nav">
                    <ul class="c-off-canvas__list">
                        <li class="c-off-canvas__item user-access">
                            <a class="c-off-canvas__link" href="/">Cities</a>
                        </li>                        
                        <li class="c-off-canvas__item">
                            <a class="c-off-canvas__link" href="/what-is-it">What is it?</a>
                        </li>
                        <li class="c-off-canvas__item">
                            <a class="c-off-canvas__link" href="/how-to-use-it">How to use it?</a>
                        </li>
                        <li class="c-off-canvas__item">
                            <a class="c-off-canvas__link" href="/get-started">Get started!</a>
                        </li>                    
                        <li class="c-off-canvas__item has-user-nav user-access">
                            <a class="c-off-canvas__link" href="/profile">Profile</a>
                            <ul class="c-off-canvas__user-nav">
                                <li class="c-off-canvas__item">
                                    <a class="c-off-canvas__link" href="/profile">Member Info</a>
                                </li>
                                <li class="c-off-canvas__item">
                                    <a class="c-off-canvas__link user-sign-out" href="">Sign out</a>
                                </li>
                            </ul>
                        </li>
                        <li class="c-off-canvas__item has-user-nav visitor-access">
                            <a class="c-off-canvas__link" href="#">Start</a>
                            <ul class="c-off-canvas__user-nav">
                                <li class="c-off-canvas__item">
                                    <a class="c-off-canvas__link" href="/register">Register</a>
                                </li>
                                <li class="c-off-canvas__item c-off-canvas__item--before-bracket">
                                    <a class="c-off-canvas__link" href="/login">Login</a>
                                </li>                                
                            </ul>
                        </li>
                    </ul>
                </nav>
                
                <a class="c-off-canvas__user" href="/profile">
                    <span class="c-site-nav__user o-flag">
                        <span class="c-site-nav__user-img o-flag__img">
                            <i class="c-site-nav__user-icon icon-user-circle-o">
                                <span class="u-hidden-visually">User:</span>
                            </i>
                        </span>
                        <span class="c-site-nav__user-body o-flag__body">
                            <span class="c-site-nav__user__name"></span>
                        </span>
                    </span>
                </a>
                
                <button class="c-off-canvas__close" id="c-off-canvas__close" type="button">
                    <i class="icon-close">
                        <span class="u-hidden-visually">close</span>
                    </i>
                </button>
            </div>

            <div class="c-off-canvas__morph-shape" id="c-off-canvas__morph-shape" data-morph-open="M-7.312,0H15c0,0,66,113.339,66,399.5C81,664.006,15,800,15,800H-7.312V0z;M-7.312,0H100c0,0,0,113.839,0,400c0,264.506,0,400,0,400H-7.312V0z">
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100 800" preserveAspectRatio="none">
                    <defs>
                        <linearGradient id="Gradient1" x1="0" x2="0" y1="0" y2="1">
                            <stop class="stop1" offset="0%" />
                            <stop class="stop2" offset="100%" />
                        </linearGradient>
                        <style type="text/css">
                            .stop1 {
                                stop-color: #00b0c4;
                            }

                            .stop2 {
                                stop-color: #16b68f;
                            }
                        </style>
                    </defs>

                    <path d="M-7.312,0H0c0,0,0,113.839,0,400c0,264.506,0,400,0,400h-7.312V0z" fill="url(#Gradient1)" />
                </svg>
            </div>
        </div>
        
        <div class="c-site-inner">
            <header class="c-site-header c-site-header--sticky">
                <div class="c-site-header__wrapper o-wrapper">                    
                    <div class="c-site-header__flag o-flag o-flag--middle">
                        <div class="c-site-header__img o-flag__img">
                            <a class="c-site-logo" href="/">
                                <strong class="u-hidden-visually">Weather App</strong>
                            </a>
                        </div>
                        <div class="c-site-header__body o-flag__body">
                            <button id="open-off-canvas" class="c-site-burger" type="button">
                                <i class="icon-burger-menu">
                                    <span class="u-hidden-visually">menu</span>
                                </i>
                            </button>
                            
                            <nav class="c-site-nav c-site-nav--primary" id="site-nav">
                                <ul class="c-site-nav__list">
                                    <li class="c-site-nav__item user-access" display="inline-block">
                                        <a class="c-site-nav__link" href="/">Cities</a>
                                    </li>
                                    <li class="c-site-nav__item">
                                        <a class="c-site-nav__link" href="/what-is-it">What is it?</a>
                                    </li>
                                    <li class="c-site-nav__item">
                                        <a class="c-site-nav__link" href="/how-to-use-it">How to use it?</a>
                                    </li>
                                    <li class="c-site-nav__item">
                                        <a class="c-site-nav__link" href="/get-started">Get started!</a>
                                    </li>
                                </ul>
                            </nav>

                            <nav class="c-site-nav c-site-nav--secondary" id="site-nav-secondary">
                                <ul class="c-site-nav__list user-access">
                                    <li class="c-site-nav__item has-dropdown">                                                    
                                        <a class="c-site-nav__link has-user" href="/profile">
                                            <span class="c-site-nav__user o-flag">
                                                <span class="c-site-nav__user-img o-flag__img">
                                                    <i class="c-site-nav__user-icon icon-user-circle-o">
                                                        <span class="u-hidden-visually">User:</span>
                                                    </i>
                                                </span>
                                                <span class="c-site-nav__user-body o-flag__body">
                                                    <span class="c-site-nav__user__name"></span>
                                                </span>
                                            </span>
                                        </a>

                                        <ul class="c-dropdown c-dropdown--sm c-dropdown--right">
                                            <li class="c-dropdown__item">
                                                <a class="c-dropdown__link" href="/profile">Member Info</a>
                                            </li>
                                            <li class="c-dropdown__item">
                                                <a class="c-dropdown__link user-sign-out" href="">Sign out</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                                <ul class="c-site-nav__list visitor-access">  
                                    <li class="c-site-nav__item">
                                        <a class="c-site-nav__link" href="/register">Register</a>                                            
                                    </li>                                            
                                    <li class="c-site-nav__item c-site-nav__item--before-bracket">
                                        <a class="c-site-nav__link" href="/login">Login</a>
                                    </li>                                            
                                </ul>
                            </nav>  
                        </div>                        
                    </div>                    
                </div>                
            </header>
            
            <div class="c-site-body">
                <div class="c-section user-access cities">
                    <div class="o-wrapper">
                        <div class="c-heading u-align-center">
                            <h1 class="u-h2 u-color-secondary u-font-medium">Cities' Weather</h1>
                            <h5 class="u-h5 u-color-primary u-font-small">Select the cities which you want to be informed about their weather.</h1>
                        </div>            
                        <div class="c-content">
                            <form action="/" method="POST" id="cities-form" autocomplete="off">
                                <div class="c-sets o-layout"></div>
                            </form>
                            
                            <div id="city-pattern" style="display: none;">                            
                                <div class="c-sets__item o-layout__item u-margin-bottom-large u-1/3@tablet" id="city_id">                            
                                    <a class="c-set">
                                        <h4 class="c-set__title">
                                            <span class="c-temprature">
                                                <span class="val"></span>
                                                <span>°C</span>
                                            </span>                                            
                                            <span class="c-name"></span>
                                        </h4>                                
                                        <span class="c-set__detail">                                    
                                            <span class="c-weather"></span>
                                        </span>
                                        <img class="c-set__image" src="/img/cities/city.jpg" alt="">
                                    </a>
                                    <div class="c-check c-check--inline u-font-size-large">
                                        <input class="c-check__input" type="checkbox" name="city_ids[]" value="">
                                        <span class="c-check__text c-check__text@unchecked">Select</span>
                                        <span class="c-check__text c-check__text@checked u-color-success-2 u-font-medium">Selected</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>            
            
                <div class="c-section user-access profile">
                    <div class="o-wrapper">            
                        <div class="c-content">
                            <div class="o-layout o-layout--reverse o-layout--has-margins<tablet">
                                <div class="o-layout__item u-3/3@desktop">
                                    <div class="c-box c-box--bare<desktop" data-equal-height="profile">
                                        <div class="c-box__header u-hide u-show@desktop">
                                            <h1 class="c-box__heading u-color-secondary" style="display: inline-block;">
                                                Member Info (ID: <span id="user-id"></span>)
                                            </h1>
                                            <div class="profile-img avatar" style="display: none; float: right;">
                                                <img src="" id="img" width="60">
                                            </div>
                                        </div>

                                        <div class="c-box__body">
                                            <h2 class="u-h4 u-font-medium">Personel Info</h2>

                                            <form action="/" method="POST" id="profile-form" enctype="multipart/form-data" autocomplete="off" class="c-profile__form">
                                                <div class="c-form">
                                                    <div class="o-layout">
                                                        <div class="o-layout__item u-1/1@tablet">
                                                            <div class="o-layout">
                                                                <div class="o-layout__item u-1/2@tablet">
                                                                    <div class="c-form__group">
                                                                        <label for="profile_name" class="c-form__label">Full name</label>

                                                                        <div class="c-form__field">
                                                                             <input class="c-form__input c-form__input--text" id="profile_name" name="name" type="text" value="" placeholder="İsminizi giriniz..." data-rule-required="true">
                                                                        </div>
                                                                    </div>

                                                                    <div class="c-form__group">
                                                                        <label for="profile_gender" class="c-form__label">Gender</label>
                                                            
                                                                        <div class="c-form__field">
                                                                            <div class="c-check-list c-check-list--inline">
                                                                                <div class="c-check-list__item">
                                                                                    <label class="c-check c-check--circle">
                                                                                         <input class="c-check__input" type="radio" id="profile_gender_female" name="gender" data-rule-required="true" value="female">
                                                                                         <span class="c-check__text">Woman</span>
                                                                                    </label>
                                                                                </div>

                                                                                <div class="c-check-list__item">
                                                                                    <label class="c-check c-check--circle">
                                                                                        <input class="c-check__input" type="radio" id="profile_gender_male" name="gender" data-rule-required="true" value="male">
                                                                                        <span class="c-check__text">Man</span>
                                                                                    </label>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>

                                                                    <div class="c-form__group">
                                                                        <label for="profile_phone" class="c-form__label">Phone</label>
                                                            
                                                                        <div class="c-form__field" id="check-phone">
                                                                            <input class="c-form__input c-form__input--text" id="profile_phone" name="phone" type="tel" value="" data-validation-length="min14" data-rule-required="true">
                                                                        </div>
                                                                    </div>
                                                                    
                                                                    <div class="c-form__group">
                                                                        <label for="profile_city" class="c-form__label">City</label>
                                                            
                                                                        <div class="c-form__field">
                                                                            <input class="c-form__input c-form__input--text" id="profile_city" name="city" type="text" value="">
                                                                        </div>
                                                                    </div>
                                                                    
                                                                    <div class="c-form__group">
                                                                        <label for="profile_timezone" class="c-form__label">Time zone</label>
                                                            
                                                                        <div class="c-form__field">
                                                                            <select name="timezone" id="profile_timezone" style="width: 100%;" data-ride="select2">
                                                                                <option value="">Select ...</option>
                                                                                <option value="Etc/GMT+12">(GMT-12:00) International Date Line West</option>
                                                                                <option value="Pacific/Midway">(GMT-11:00) Midway Island, Samoa</option>
                                                                                <option value="Pacific/Honolulu">(GMT-10:00) Hawaii</option>
                                                                                <option value="US/Alaska">(GMT-09:00) Alaska</option>
                                                                                <option value="America/Los_Angeles">(GMT-08:00) Pacific Time (US & Canada)</option>
                                                                                <option value="America/Tijuana">(GMT-08:00) Tijuana, Baja California</option>
                                                                                <option value="US/Arizona">(GMT-07:00) Arizona</option>
                                                                                <option value="America/Chihuahua">(GMT-07:00) Chihuahua, La Paz, Mazatlan</option>
                                                                                <option value="US/Mountain">(GMT-07:00) Mountain Time (US & Canada)</option>
                                                                                <option value="America/Managua">(GMT-06:00) Central America</option>
                                                                                <option value="US/Central">(GMT-06:00) Central Time (US & Canada)</option>
                                                                                <option value="America/Mexico_City">(GMT-06:00) Guadalajara, Mexico City, Monterrey</option>
                                                                                <option value="Canada/Saskatchewan">(GMT-06:00) Saskatchewan</option>
                                                                                <option value="America/Bogota">(GMT-05:00) Bogota, Lima, Quito, Rio Branco</option>
                                                                                <option value="US/Eastern">(GMT-05:00) Eastern Time (US & Canada)</option>
                                                                                <option value="US/East-Indiana">(GMT-05:00) Indiana (East)</option>
                                                                                <option value="Canada/Atlantic">(GMT-04:00) Atlantic Time (Canada)</option>
                                                                                <option value="America/Caracas">(GMT-04:00) Caracas, La Paz</option>
                                                                                <option value="America/Manaus">(GMT-04:00) Manaus</option>
                                                                                <option value="America/Santiago">(GMT-04:00) Santiago</option>
                                                                                <option value="Canada/Newfoundland">(GMT-03:30) Newfoundland</option>
                                                                                <option value="America/Sao_Paulo">(GMT-03:00) Brasilia</option>
                                                                                <option value="America/Argentina/Buenos_Aires">(GMT-03:00) Buenos Aires, Georgetown</option>
                                                                                <option value="America/Godthab">(GMT-03:00) Greenland</option>
                                                                                <option value="America/Montevideo">(GMT-03:00) Montevideo</option>
                                                                                <option value="America/Noronha">(GMT-02:00) Mid-Atlantic</option>
                                                                                <option value="Atlantic/Cape_Verde">(GMT-01:00) Cape Verde Is.</option>
                                                                                <option value="Atlantic/Azores">(GMT-01:00) Azores</option>
                                                                                <option value="Africa/Casablanca">(GMT+00:00) Casablanca, Monrovia, Reykjavik</option>
                                                                                <option value="Etc/Greenwich">(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London</option>
                                                                                <option value="Europe/Amsterdam">(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna</option>
                                                                                <option value="Europe/Belgrade">(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague</option>
                                                                                <option value="Europe/Brussels">(GMT+01:00) Brussels, Copenhagen, Madrid, Paris</option>
                                                                                <option value="Europe/Sarajevo">(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb</option>
                                                                                <option value="Africa/Lagos">(GMT+01:00) West Central Africa</option>
                                                                                <option value="Asia/Amman">(GMT+02:00) Amman</option>
                                                                                <option value="Europe/Athens">(GMT+02:00) Athens, Bucharest, Istanbul</option>
                                                                                <option value="Asia/Beirut">(GMT+02:00) Beirut</option>
                                                                                <option value="Africa/Cairo">(GMT+02:00) Cairo</option>
                                                                                <option value="Africa/Harare">(GMT+02:00) Harare, Pretoria</option>
                                                                                <option value="Europe/Helsinki">(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius</option>
                                                                                <option value="Asia/Jerusalem">(GMT+02:00) Jerusalem</option>
                                                                                <option value="Europe/Minsk">(GMT+02:00) Minsk</option>
                                                                                <option value="Africa/Windhoek">(GMT+02:00) Windhoek</option>
                                                                                <option value="Asia/Kuwait">(GMT+03:00) Kuwait, Riyadh, Baghdad</option>
                                                                                <option value="Europe/Moscow">(GMT+03:00) Moscow, St. Petersburg, Volgograd</option>
                                                                                <option value="Africa/Nairobi">(GMT+03:00) Nairobi</option>
                                                                                <option value="Asia/Tbilisi">(GMT+03:00) Tbilisi</option>
                                                                                <option value="Asia/Tehran">(GMT+03:30) Tehran</option>
                                                                                <option value="Asia/Muscat">(GMT+04:00) Abu Dhabi, Muscat</option>
                                                                                <option value="Asia/Baku">(GMT+04:00) Baku</option>
                                                                                <option value="Asia/Yerevan">(GMT+04:00) Yerevan</option>
                                                                                <option value="Asia/Kabul">(GMT+04:30) Kabul</option>
                                                                                <option value="Asia/Yekaterinburg">(GMT+05:00) Yekaterinburg</option>
                                                                                <option value="Asia/Karachi">(GMT+05:00) Islamabad, Karachi, Tashkent</option>
                                                                                <option value="Asia/Calcutta">(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</option>
                                                                                <option value="Asia/Calcutta">(GMT+05:30) Sri Jayawardenapura</option>
                                                                                <option value="Asia/Katmandu">(GMT+05:45) Kathmandu</option>
                                                                                <option value="Asia/Almaty">(GMT+06:00) Almaty, Novosibirsk</option>
                                                                                <option value="Asia/Dhaka">(GMT+06:00) Astana, Dhaka</option>
                                                                                <option value="Asia/Rangoon">(GMT+06:30) Yangon (Rangoon)</option>
                                                                                <option value="Asia/Bangkok">(GMT+07:00) Bangkok, Hanoi, Jakarta</option>
                                                                                <option value="Asia/Krasnoyarsk">(GMT+07:00) Krasnoyarsk</option>
                                                                                <option value="Asia/Hong_Kong">(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi</option>
                                                                                <option value="Asia/Kuala_Lumpur">(GMT+08:00) Kuala Lumpur, Singapore</option>
                                                                                <option value="Asia/Irkutsk">(GMT+08:00) Irkutsk, Ulaan Bataar</option>
                                                                                <option value="Australia/Perth">(GMT+08:00) Perth</option>
                                                                                <option value="Asia/Taipei">(GMT+08:00) Taipei</option>
                                                                                <option value="Asia/Tokyo">(GMT+09:00) Osaka, Sapporo, Tokyo</option>
                                                                                <option value="Asia/Seoul">(GMT+09:00) Seoul</option>
                                                                                <option value="Asia/Yakutsk">(GMT+09:00) Yakutsk</option>
                                                                                <option value="Australia/Adelaide">(GMT+09:30) Adelaide</option>
                                                                                <option value="Australia/Darwin">(GMT+09:30) Darwin</option>
                                                                                <option value="Australia/Brisbane">(GMT+10:00) Brisbane</option>
                                                                                <option value="Australia/Canberra">(GMT+10:00) Canberra, Melbourne, Sydney</option>
                                                                                <option value="Australia/Hobart">(GMT+10:00) Hobart</option>
                                                                                <option value="Pacific/Guam">(GMT+10:00) Guam, Port Moresby</option>
                                                                                <option value="Asia/Vladivostok">(GMT+10:00) Vladivostok</option>
                                                                                <option value="Asia/Magadan">(GMT+11:00) Magadan, Solomon Is., New Caledonia</option>
                                                                                <option value="Pacific/Auckland">(GMT+12:00) Auckland, Wellington</option>
                                                                                <option value="Pacific/Fiji">(GMT+12:00) Fiji, Kamchatka, Marshall Is.</option>
                                                                                <option value="Pacific/Tongatapu">(GMT+13:00) Nuku'alofa</option>
                                                                             </select>
                                                                         </div>
                                                                    </div>
                                                                    <div class="c-form__group">
                                                                        <label for="profile_language" class="c-form__label">Language</label>                                                            
                                                            
                                                                        <div class="c-form__field">
                                                                            <select class="c-form__input" id="profile_language" name="cid" style="width: 100%;" data-ride="select2">
                                                                                <option value="">Select ...</option>
                                                                                <option value="tr">Turkish</option>
                                                                                <option value="en">English</option>
                                                                            </select>
                                                                        </div>                                                            
                                                                    </div>
                                                                    
                                                                    <div class="c-form__group">
                                                                        <label for="profile_image" class="c-form__label">Photo</label>

                                                                        <div class="c-form__field" id="profile_image">
                                                                            <input name="image" type="file" id="profile-image" class="c-form__input">
                                                                            <button id="upload-profile-image" class="c-btn c-btn--small c-btn--secondary" type="button" style="margin: 6px 0;">Upload</button>
                                                                        </div>
                                                                        <div class="profile-img" style="display: none;">
                                                                            <img src="" id="img" height="100">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <h2 class="u-h4 u-font-medium u-padding-top-large">
                                                     Subscription Information
                                                </h2>   
                                                                             
                                                <div class="c-form">
                                                    <div class="o-layout">
                                                        <div class="o-layout__item u-6/6@tablet">
                                                            <div class="paid-subscriber" style="display: none;">
                                                                <h3 style="font-size: 18px;">You are a paid subscriber. Do you have a promotion code?</h3>
                                                                
                                                                <div class="c-form__group">
                                                                    <label for="profile_email" class="c-form__label">Enter your promotion code:</label>

                                                                    <div class="c-form__field" id="coupon">
                                                                        <input id="coupon" name="coupon" type="text" value="" placeholder="" class="c-form__input c-form__input--text" style="display: inline-block; width: auto;">
                                                                        <button id="check-coupon" class="c-btn c-btn--small c-btn--secondary" type="button">Check</button>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="free-subscriber" style="display: none;">
                                                                <h3 style="font-size: 18px;">You are a free subscriber activated on <span class="coupon_added" style="color: green; font-weight: 900;"></span></h3>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <h2 class="u-h4 u-font-medium u-padding-top-large">
                                                     Account Information
                                                </h2>                                

                                                <div class="c-form">
                                                    <div class="o-layout">
                                                        <div class="o-layout__item u-5/6@tablet">
                                                            <div class="o-layout">
                                                                <div class="o-layout__item u-1/2">
                                                                    <div class="c-form__group">
                                                                        <label for="profile_email" class="c-form__label">Email</label>

                                                                        <div class="c-form__field" id="check-email">
                                                                            <input class="c-form__input c-form__input--text" id="profile_email" name="email" type="email" value="" placeholder="ornek@email.com" data-validation="email required" data-rule-required="true">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>

                                                            <div class="o-layout">
                                                                <div class="o-layout__item u-1/2">
                                                                    <div class="c-form__group">
                                                                        <label for="profile_password" class="c-form__label">Password</label>
                                                            
                                                                        <div class="c-form__field">
                                                                             <input class="c-form__input c-form__input--text" id="profile_password" name="password" type="password" placeholder="" data-validation="confirmation" data-validation-confirm="password_confirm" data-rule-required="true">
                                                                        </div>
                                                                    </div>
                                                                </div>                                                    
                                                            
                                                                <div class="o-layout__item u-1/2">
                                                                    <div class="c-form__group">
                                                                        <label for="profile_password_confirm" class="c-form__label">Password again</label>
                                                            
                                                                        <div class="c-form__field">
                                                                             <input class="c-form__input c-form__input--text" id="profile_password_confirm" name="password_confirm" type="password" placeholder="" data-rule-required="true">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>                                        
                                                </div>
                                    
                                                <div class="c-form__group c-form__group--submit u-margin-bottom-none u-align-right">
                                                    <button class="c-btn c-btn--small c-btn--secondary" type="submit">Save</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="c-section c-section--register visitor-access register">
                    <div class="o-wrapper">
                        <div class="c-heading u-align-center">
                            <h1 class="u-h2 u-color-secondary u-font-medium">Register</h1>
                        </div>

                        <div class="c-content">
                            <div class="c-auth">
                                <form class="c-auth__form" id="register-form" method="POST" action="/">       
                                    <div class="c-form">
                                        <div class="c-form__group">
                                            <label for="register_name" class="c-form__label">Full name</label>
                                            <div class="c-form__field">
                                                <input class="c-form__input c-form__input--text" id="register_name" name="name" type="text" value="" placeholder="" data-validation="required" data-rule-required="true">
                                            </div>
                                        </div>

                                        <div class="c-form__group">
                                            <label for="register_email" class="c-form__label">Email</label>

                                            <div class="c-form__field" id="check-email">
                                                <input class="c-form__input c-form__input--text" id="register_email" name="email" type="email" value="" placeholder="" data-validation="required email" data-rule-required="true">
                                            </div>
                                        </div>

                                        <div class="c-form__group">
                                            <label for="register_phone" class="c-form__label">Phone</label>
                                    
                                            <div class="c-form__field" id="check-phone">
                                                <input class="c-form__input c-form__input--text" id="register_phone" name="phone" type="tel" value="" placeholder="" data-validation="required length" data-validation-length="5-20" data-rule-required="true">
                                            </div>
                                        </div>

                                        <div class="c-form__group">
                                            <label for="register_gender" class="c-form__label">Gender</label>
                                            <div class="c-form__field">
                                                <div class="c-check-list c-check-list--inline">
                                                    <div class="c-check-list__item">
                                                        <label class="c-check c-check--circle">
                                                            <input class="c-check__input" type="radio" id="register_gender_female" name="gender" data-rule-required="true" value="female">
                                                            <span class="c-check__text">Woman</span>
                                                        </label>
                                                    </div>
                                            
                                                    <div class="c-check-list__item">
                                                        <label class="c-check c-check--circle">
                                                            <input class="c-check__input" type="radio" id="register_gender_male" name="gender" data-rule-required="true" value="male">
                                                            <span class="c-check__text">Man</span>
                                                        </label>
                                                    </div>    
                                                </div>
                                            </div>
                                        </div>

                                        <div class="c-form__group">
                                            <label for="register_password" class="c-form__label">Password</label>
                                            <div class="c-form__field">
                                                <input class="c-form__input c-form__input--text" id="register_password" name="password" type="password" placeholder="" data-validation="length required" data-validation-length="min7" data-rule-required="true">
                                            </div>
                                        </div>

                                        <div class="c-form__group">
                                            <label for="register_password_confirm" class="c-form__label">Password again</label>
                                            <div class="c-form__field">
                                                <input class="c-form__input c-form__input--text" id="register_password_confirm" name="password_confirm" type="password" placeholder="" data-validation="confirmation" data-validation-confirm="password" data-rule-required="true">
                                            </div>
                                        </div>    
                                        <div class="c-form__group">
                                            <label class="c-check">
                                                <input class="c-check__input" type="checkbox" id="opt_in_aggrement" name="tos_pp_aggreed" data-validation="required" data-rule-required="true">
                                                <span class="c-check__text">Confirm Agreement</span>
                                            </label>
                                        </div>

                                        <div class="c-form__group c-form__group--submit u-margin-bottom-none">
                                            <button class="c-btn c-btn--block c-btn--secondary" type="submit">Register</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <div class="u-align-center u-padding-top">
                                <p>
                                    Have an account?
                                    <br>
                                    <a href="/login" class="u-color-secondary u-font-medium">Login</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="c-section c-section--login visitor-access login">                    
                    <div class="o-wrapper">                
                        <div class="c-heading u-align-center">
                            <h1 class="u-h2 u-color-secondary u-font-medium">Login</h1>
                        </div>

                        <div class="c-content">                    
                            <div class="c-auth">
                                <form class="c-auth__form" id="login-form" method="post" action="/" autocomplete="off"> 
                                    <div class="o-layout">
                                        <div class="c-form o-layout__item">
                                            <div class="c-form__group">        
                                                <label for="login_email" class="c-form__label">Email</label>

                                                <div class="c-form__field">
                                                    <input class="c-form__input c-form__input--text" id="login_email" name="email" type="email" placeholder="" data-validation="email required"  data-rule-required="true">
                                                </div>
                                            </div>

                                            <div class="c-form__group">
                                                <label for="login_password" class="c-form__label">Password</label>

                                                <div class="c-form__field">
                                                    <input class="c-form__input c-form__input--text" id="login_password" name="password" type="password" placeholder="*********" data-validation="length required" data-validation-length="min6" data-rule-required="true">
                                                </div>
                                            </div>

                                            <!-- 
                                            <div class="c-form__group">
                                                <div class="o-layout">
                                                    <div class="o-layout__item u-1/2">
                                                        <label class="c-check">
                                                            <input class="c-check__input" type="checkbox" id="opt_in" name="remember" data-rule-required="true">
                                                            <span class="c-check__text">Remember me</span>
                                                        </label>
                                                    </div>

                                                    <div class="o-layout__item u-1/2 u-align-right">
                                                        <a href="" class="u-nowrap u-color-secondary">Forgot password</a>
                                                    </div>
                                                </div>
                                            </div>
                                             -->

                                            <div class="c-form__group c-form__group--submit u-margin-bottom-none">
                                                <button class="c-btn c-btn--block c-btn--secondary" type="submit">Login</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>                        
                            </div>

                            <div class="u-align-center u-padding-top">
                                <p>
                                    Not registered yet!
                                    <br>
                                    <a href="/register" class="u-color-secondary u-font-medium">Register now</a>
                                </p>
                            </div>                    
                        </div>
                    </div>
                </div>
            </div>
                
            <div class="c-section what-is-it">                    
                <div class="o-wrapper">                
                    <div class="c-heading u-align-center">
                        <h1 class="u-h2 u-color-secondary u-font-medium">What is it?</h1>
                    </div>

                    <div class="c-content">
                        <p>What is it?</p>
                        <p>Write the article here ...</p>
                    </div>
                </div>
            </div>
                
            <div class="c-section how-to-use-it">                    
                <div class="o-wrapper">                
                    <div class="c-heading u-align-center">
                        <h1 class="u-h2 u-color-secondary u-font-medium">How to use it?</h1>
                    </div>

                    <div class="c-content">
                        <p>How to use it?</p>
                        <p>Write the article here ...</p>
                    </div>
                </div>
            </div>
                
            <div class="c-section get-started">                    
                <div class="o-wrapper">                
                    <div class="c-heading u-align-center">
                        <h1 class="u-h2 u-color-secondary u-font-medium">Get started!</h1>
                    </div>

                    <div class="c-content">
                        <p>Get started!</p>
                        <p>Write the article here ...</p>
                    </div>
                </div>
            </div>
                
            <div class="c-section not-found">                    
                <div class="o-wrapper">                
                    <div class="c-heading u-align-center">
                        <br>
                        <br>
                        <br>
                        <h1 class="u-h2 u-color-secondary u-font-medium" style="font-size: 40px !important;">404<br>NOT FOUND PAGE!</h1>
                    </div>
                </div>
            </div>
            
            <footer>
                <div class="o-wrapper">
                    <div class="u-align-center u-padding-small">
                        <div>© 2020 Weather App. All rights reserved.</div>
                    </div>
                </div>                
            </footer>
        </div>
    </div>

    <script src="/vendor/svgxuse.min.js"></script>
    <script src="/vendor/jquery-3.1.1.min.js"></script>
    <script src="/vendor/jquery.easing.min.js"></script>
    <script src="/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="/vendor/select2/js/select2.full.min.js"></script>
    <script src="/vendor/classie.js"></script>
    <script src="/vendor/transition.js"></script>
    <script src="/vendor/collapse.js"></script>
    <script src="/vendor/tooltip.js"></script>
    <script src="/vendor/popover.js"></script>
    <script src="/vendor/classie.js"></script>
    <script src="/vendor/jquery.matchHeight-min.js"></script>
    <script src="/vendor/slick/slick.min.js"></script>
    <script src="/vendor/garand-sticky/jquery.sticky.js"></script>
    <script src="/js/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.min.js"></script>
    <script src="https://lab.alexcican.com/set_cookies/cookie.js"></script>
    <script type="text/javascript">
    var base_url       = '<?php echo $base_url; ?>';
    var auth_url       = '<?php echo $auth_url; ?>';
    var token_url      = '<?php echo $token_url; ?>';
    var user_url       = '<?php echo $user_url; ?>';
    var cities_url     = '<?php echo $cities_url; ?>';
    var coupon_url     = '<?php echo $coupon_url; ?>';
    var prf_upload_url = '<?php echo $prf_upload_url; ?>';
    var client_id      = '<?php echo $client_id; ?>';
    var client_secret  = '<?php echo $client_secret; ?>';
    var is_logged_in   = false;
    var width          = $(window).width();
	var message_top    = '100px';
    var message_left   = '30%';

    if ( width < 1024 ) {
   		message_left   = '20%';
	}                		

	if ( width < 768 ) {
   		message_top    = '70px';
        message_left   = '10%';
	}

	if ( width < 540 ) {
	    message_top  = '50px';
	    message_left = '2%';
	}
    </script>
    <script src="/js/app.js"></script>
</body>
</html>
